server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "murcia2024"
    sources:
      youtube: true
      soundcloud: true
      http: true
plugins:
  youtube:
    enabled: true
    allowSearch: true
